import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import { type ReactNode } from 'react'
import Head from 'next/head'

export default function App ({ Component, pageProps }: AppProps): ReactNode {
  return <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&family=Noto+Sans:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
      />
    </Head>
    <Component {...pageProps} />
    </>
}
